### ISSUE TITLE
Running Hotword.py

### ISSUE THREAD

**Issue by acla6525** [BlackLight/assistant-sample#1]
I am having trouble running the hotword script, I have entered the path to my model file but it keeps saying no module named snowboy, even though I have sent the 3 wav files to the server successfully. See below terminal output, any help would be appreciated.

(env) pi@raspberrypi:~ $ python /home/pi/assistant-sample/hotword_sample.py
Traceback (most recent call last):
  File "/home/pi/assistant-sample/assistant/hotword.py", line 7, in <module>
    import snowboydecoder
ModuleNotFoundError: No module named 'snowboydecoder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/assistant-sample/hotword_sample.py", line 2, in <module>
    from assistant.hotword import HotwordService
  File "/home/pi/assistant-sample/assistant/hotword.py", line 9, in <module>
    import snowboy.snowboydecoder as snowboydecoder
ModuleNotFoundError: No module named 'snowboy'

**Comment by samiron7567** [comment]
I am not sure if you have installed snowboy module before executing. However following the documentation i tried to install snowboy on my RPi4 with Raspbian Buster and had to fail again installing. Looks like Raspbian Buster has lot of issues currently and not fully stable to use or most of the libraries not compatible with the latest Buster. However the pain point is, you can not go back to Raspbian Stretch or any earlier version if you are on RPi4.
